spring:
  application:
    name: secret-user
  cloud:
    nacos:
#      server-addr: 127.0.0.1:8848
      server-addr: 92.113.117.22:10846

#      password: nacos
#      username: nacos
      discovery:
#        server-addr: 127.0.0.1:8848
        server-addr: 92.113.117.22:10846
      config:
        timeout: 300000
  config:
    import: optional:nacos:secretblog_user_application.yaml