spring:
  application:
    name: secret-gateway
  config:
    import: optional:nacos:secretblog_gateway_application.yml

  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
#      server-addr: 178.92.75.5:11346

      password: nacos
#      password: nacos
#      username: nacos
      discovery:
        server-addr: 127.0.0.1:8848
#        server-addr: 178.92.75.5:11346
      config:
        server-addr: 127.0.0.1:8848
#        server-addr: 178.92.75.5:11346
        timeout: 300000


