#Docker環境配置
spring:
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR}
      discovery:
        server-addr: ${NACOS_SERVER_ADDR}
      config:
        server-addr: ${NACOS_SERVER_ADDR}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      database: ${REDIS_DATABASE}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: ${REDIS_SSL_ENABLED}
  config:
    import: optional:nacos:secretblog_gateway_application.yaml
#JwtToken相關
local:
  jwt:
    private-key: ${LOCAL_JWT_PRIVATE_KEY}
    public-key: ${LOCAL_JWT_PUBLIC_KEY}
