spring:
  application:
    name: secret-article
  cloud:
    nacos:
      server-addr: 178.92.75.5:11346
#      password: nacos
#      username: nacos
      discovery:
        server-addr: 178.92.75.5:11346
      config:
        timeout: 300000
        file-extension: yml
        group: DEFAULT_GROUP
  config:
    import: optional:nacos:secretblog_article_application.yaml